### ISSUE TITLE
Window content not re-drawn after switching workspaces in i3 

### ISSUE THREAD

**Issue by valters-tomsons** [valters-tomsons/spectabis-next#5]
Using i3wm (i3-gaps).

Launch a GUI window, switch to another workspace and after couple of seconds switch back to the Spectabis workspace.

Window will appear fully transparent for a few seconds or until user interaction.

_Probably an issue with Avalonia UI._

**Comment by FaithLV** [comment]
Does not happen when using Windows 10 Workspaces.

**Comment by FaithLV** [comment]
Tracking: https://github.com/AvaloniaUI/Avalonia/issues/3460
